#!/usr/bin/env bash

## Add user for testing roles and permissions
##
## Usage: fin test-users

  fin drush user:password admin "admin"

  fin drush user:create site_admin_approver --password="siteadmin"
  fin drush user:role:add "site_admin" site_admin_approver
  fin drush group:user:add site_admin_approver 1 'public_content-approver'

  fin drush user:create site_admin_contributor --password="siteadmin"
  fin drush user:role:add "site_admin" site_admin_contributor
  fin drush group:user:add site_admin_contributor 1 'public_content-contributor'

  fin drush user:create site_admin_reviewer --password="siteadmin"
  fin drush user:role:add "site_admin" site_admin_reviewer
  fin drush group:user:add site_admin_reviewer 1 'public_content-reviewer'

  fin drush user:create site_editor_approver --password="siteeditor"
  fin drush user:role:add "site_editor" site_editor_approver
  fin drush group:user:add site_editor_approver 1 'public_content-approver'

  fin drush user:create site_editor_contributor --password="siteeditor"
  fin drush user:role:add "site_editor" site_editor_contributor
  fin drush group:user:add site_editor_contributor 1 'public_content-contributor'

  fin drush user:create site_editor_reviewer --password="siteeditor"
  fin drush user:role:add "site_editor" site_editor_reviewer
  fin drush group:user:add site_editor_reviewer 1 'public_content-reviewer'
